### ISSUE TITLE
bug of `bytearray_between` function

### ISSUE THREAD

**Issue by m1n999999** [aiken-lang/fuzz#14]
```rust
pub fn bytearray_between(min: Int, max: Int) -> Fuzzer<ByteArray> {
  if max < min {
    bytearray_between(max, min)
  } else if max <= 0 {
    constant("")
  } else {
    expect min >= 0
    let size <- and_then(int_between(min, max))
    if size <= 32 {
      map(bytearray(), builtin.slice_bytearray(0, size, _))
    } else {
      let head <- and_then(bytearray())
      let tail <- map(bytearray_between(0, size - 32))
      builtin.append_bytearray(head, tail)
    }
  }
}
```
Each test created with this function fails if `size` > 32. `tail` must be a ByteArray whose length must be exactly `size - 32`, not be between `0` and `size - 32`.

**Comment by KtorZ** [comment]
@m1n999999 I don't think I agree. `head` is a bytearray of exactly `32` bytes, and so `tail` must be anything between `0` and `size - 32` so that the resulting length is between `32` and `size - 32 + 32 = size`. This works well because we know that `size` is at least `32`. So we effectly generate bytearrays by chunks of `32` bytes. 

This is also confirmed by the following property test:

```ak
fn bytearray_between() -> Fuzzer<(Int, Int, ByteArray)> {
  let min <- and_then(int_between(0, 32))
  let max <- and_then(int_between(min, 10 * min))
  let bytes <- map(fuzz.bytearray_between(min, max))
  (min, max, bytes)
}

test prop_bytearray_between(params via bytearray_between()) {
  let (min, max, bytes) = params

  let len = bytearray.length(bytes)

  label(
    if len > 32 {
      @"> 32"
    } else {
      @"<= 32"
    },
  )

  len >= min && len <= max
}
```

<img width="459" alt="image" src="https://github.com/aiken-lang/fuzz/assets/5680256/39fd6e30-57d5-4ff0-addd-1e065dad8a60">

**Comment by KtorZ** [comment]
There's indeed a problem when `min` is `> 32` to begin with. The property above fails to capture this  because it doesn't pick large enough `min`. But If instead we do:

```ak
  let min <- and_then(int_between(0, 50))
```

We find a counter-example quite immediately:

```
    ┍━ aiken/fuzz.test ━━━━━━━━━━━━━━━━━━━━━━━━━
    │ FAIL [after 1 test] prop_bytearray_between
    │ × counterexample
    │ │ (
    │ │   33,
    │ │   33,
    │ │   #"9ee6dfb61a2fb903df487c401663825643bb825d41695e63df8af6162ab145a6",
    │ │ )
    ┕━━━━━━━━━━━━━━━━━━ with --seed=3362286324 → 1 tests | 0 passed | 1 failed
```
